#spring:
#  datasource:
#    username: root
#    password: 9988
#    url: jdbc:mysql://localhost:3306/db
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update